Update read me (add intro, license and funding section)
Open-EO/openeo-sentinelhub-python-driver pull request #64
Opened 2023-11-21 11:11 UTC by dthiex

For the openEM project we need to add some function section to the repository.

Suggestion is based on other examples I found within the project ([zen library](https://github.com/Open-Earth-Monitor/zen/blob/main/README.md#license)) and the company ([eo-learn](https://github.com/sentinel-hub/eo-learn#license)).

2023-11-22 12:59 UTC, zcernigoj requested changes

2023-11-22 12:59 UTC, zcernigoj commented on README.md
> +The backend can be accessed either directly via existing Sentinel Hub credentials (ClientID + Secret), but is also integrated into the [openEO Platform](https://openeo.cloud/) (EGI Check-in).
This sentence is a bit strange. Usually it's `either x or y`. Focusing on the beginning of the sentence, the backend itself is accessible without credentials - this sentence as a whole talks about authentication.

I would change this to:
Authentication on the backend can be done either with existing Sentinel Hub credentials (ClientID + Secret) or with openEO Platform credentials (EGI Check-in).

(I left out the integration with openEO Platform for simplicity)

2023-11-27 08:14 UTC, dthiex commented on README.md
> +The backend can be accessed either directly via existing Sentinel Hub credentials (ClientID + Secret), but is also integrated into the [openEO Platform](https://openeo.cloud/) (EGI Check-in).
Improved

2023-11-27 08:32 UTC, zcernigoj commented on README.md
> +The backend can be accessed either directly via existing Sentinel Hub credentials (ClientID + Secret), but is also integrated into the [openEO Platform](https://openeo.cloud/) (EGI Check-in).
Thanks, the way you wrote is even better now.

2023-11-27 08:32 UTC, zcernigoj approved these changes

2023-11-28 16:34 UTC, merged